FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine-arm32v AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine-arm32v
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "IoTEdge.Template.dll"]
